services:
  app:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
#    env_file:
#      - backend/.env
